use_frameworks!
target 'VectorSwift_Tests' do
  pod 'VectorSwift', :path => '../'
  
	pod 'Quick', :git => 'https://github.com/ikesyo/Quick.git', :branch => 'xcode8-beta6'
	pod 'Nimble', :git => 'https://github.com/ikesyo/Nimble.git', :branch => 'swift3-beta-6'
end
