use_frameworks!
target 'VectorSwift_Tests' do
  pod 'VectorSwift', :path => '../'
  
	pod 'Quick', :git => 'https://github.com/ikesyo/Quick.git', :branch => 'xcode8-beta6'
	pod 'Nimble', :git => 'https://github.com/ikesyo/Nimble.git', :branch => 'swift3-beta-6'

	post_install do |installer|
		installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
				config.build_settings['SWIFT_VERSION'] = '3.0'
			end
		end
	end
end
